import { AddOpportunityField } from '../helpers/Api/models';

export const OpportunityDefaultFields: AddOpportunityField[] = [
  {
    description: 'Opportunity Name',
    valueFormatDesc: 'ALPHANUMERIC',
    attributeType: 'desc',
    valueFormat: 'ALPHANUMERIC',
    valuesExist: false,
  },
  {
    description: 'Stage',
    valueFormatDesc: 'ALPHANUMERIC',
    attributeType: 'stage',
    valueFormat: 'ALPHANUMERIC',
    valuesExist: true,
    reduxKey: 'crmOpportunityStage',
  },
  {
    description: 'Customer',
    valueFormatDesc: 'ALPHANUMERIC',
    attributeType: 'customerName',
    valueFormat: 'ALPHANUMERIC',
    disabled: true,
  },
  {
    description: 'Owner',
    valueFormatDesc: 'ALPHANUMERIC',
    attributeType: 'userId',
    valueFormat: 'ALPHANUMERIC',
  },
  {
    description: 'Opportunity Type',
    attributeType: 'oppRecordType',
    valueFormatDesc: 'ALPHANUMERIC',
    valueFormat: 'ALPHANUMERIC',
    disabled: true,
  },
  {
    description: 'Close Date',
    attributeType: 'endDate',
    valueFormatDesc: 'DATE',
    valueFormat: 'DATE',
  },
  {
    description: 'Currency',
    attributeType: 'currency',
    valueFormatDesc: 'ALPHANUMERIC',
    valueFormat: 'ALPHANUMERIC',
    valuesExist: true,
    reduxKey: 'currency',
  },
  {
    description: 'Opp Value',
    attributeType: 'estimatedValue',
    valueFormatDesc: 'NUMERIC',
    valueFormat: 'NUMERIC',
  },
  {
    description: 'Area',
    attributeType: 'area',
    valueFormatDesc: 'ALPHANUMERIC',
    valueFormat: 'ALPHANUMERIC',
    valuesExist: true,
    reduxKey: 'crmAreaInfo',
  },
  {
    description: 'Forecast Category',
    attributeType: 'forecastCategory',
    valueFormatDesc: 'ALPHANUMERIC',
    valueFormat: 'ALPHANUMERIC',
    valuesExist: true,
    reduxKey: 'forecastInfo',
  },
];
