export const OpportunityFilterOpions = [{
    value:'A0',
    selectParam:'selectStage'
},
{
    value:'A1',
    selectParam:'selectStage'
},
{
    value:'A2',
    selectParam:'selectStage'
},
{
    value:'A3',
    selectParam:'selectStage'
},
{
    value:'A4',
    selectParam:'selectStage'
},
{
    value:'A5',
    selectParam:'selectStage'
},
{
    value:'A6',
    selectParam:'selectStage'
},
{
    value:'CL',
    selectParam:'selectStage'
},
{
    value:'Q1',
    selectParam:'selectQtr'
},
{
    value:'Q2',
    selectParam:'selectQtr'
},
{
    value:'Q3',
    selectParam:'selectQtr'
},
{
    value:'Q4',
    selectParam:'selectQtr'
},
{
    value:'License Opportunity',
    selectParam:'selectOpportunityType'
},
{
    value:'Iptor/Managed Services',
    selectParam:'selectOpportunityType'
},
{
    value:'PS Opportunity',
    selectParam:'selectOpportunityType'
},
{
    value:'*None',
    selectParam:'selectOpportunityType'
},

]