export const opptHeaders = [
  { label: 'Opportunity Id', key: 'opportunityId' },
  { label: 'Desc', key: 'desc' },
  { label: 'Customer', key: 'customer' },
  { label: 'Name', key: 'name' },
  { label: 'Owner', key: 'handler' },
  { label: 'Salesman', key: 'salesman' },
  { label: 'Area', key: 'area' },
  { label: 'Stage', key: 'stage' },
  { label: 'Probability', key: 'probability' },
  { label: 'Reason', key: 'reason' },
  { label: 'Estimated Value', key: 'estValue' },
  { label: 'Currency', key: 'currency' },
  { label: 'Active', key: 'activ' },
  { label: 'RootId', key: 'rootId' },
  { label: 'Opportunity Record Type', key: 'oppRecordType' },
  { label: 'Forecast Category', key: 'forecastCategory' },
  { label: 'ExchangeRate', key: 'exchangeRate' },
  { label: 'EstValueSys', key: 'estValueSys' },
  { label: 'ApprovalStatus', key: 'approvalStatus' },
  { label: 'LogExist', key: 'logExist' },
  { label: 'NoteExist', key: 'noteExist' },
  { label: 'ContactExist', key: 'contactExist' },
  { label: 'TaskExist', key: 'taskExist' },
  { label: 'ItemExist', key: 'itemExist' },
  { label: 'AttributeExist', key: 'attributeExist' },
  { label: 'ATRTST1', key: 'ATRTST1' },
  { label: 'ATRTST2', key: 'ATRTST2' },
  { label: 'ACTION_PENDING', key: 'ACTION_PENDING' },
  { label: 'CLOUD_OPP_SIZING', key: 'CLOUD_OPP_SIZING' },
  { label: 'CLOUD_Y1', key: 'CLOUD_Y1' },
  { label: 'CLOUD_Y2', key: 'CLOUD_Y2' },
  { label: 'CLOUD_Y3', key: 'CLOUD_Y3' },
  { label: 'CLOUD_Y4', key: 'CLOUD_Y4' },
  { label: 'CLOUD_Y5', key: 'CLOUD_Y5' },
  { label: 'CLOUD_Y6', key: 'CLOUD_Y6' },
  { label: 'CLOUD_Y7', key: 'CLOUD_Y7' },
  { label: 'CMP_ONE_OFF_FEE', key: 'CMP_ONE_OFF_FEE' },
  { label: 'CMS_PRESALE_CONS', key: 'CMS_PRESALE_CONS' },
  { label: 'CONTACT_TERM_M', key: 'CONTACT_TERM_M' },
  { label: 'ENTER_ILF_OPP_VALUE', key: 'ENTER_ILF_OPP_VALUE' },
  { label: 'LEADSOURCE', key: 'LEADSOURCE' },
  { label: 'LICENSE_CATEGORY', key: 'LICENSE_CATEGORY' },
  { label: 'LICENSE_SUM', key: 'LICENSE_SUM' },
  { label: 'MAINT_SUPP_FIRST_Y', key: 'MAINT_SUPP_FIRST_Y' },
  { label: 'NEXTSTEP', key: 'NEXTSTEP' },
  { label: 'PARTNER', key: 'PARTNER' },
  { label: 'PBU', key: 'PBU' },
  { label: 'PRESALE_CONULTANT', key: 'PRESALE_CONULTANT' },
  { label: 'PS_REVENUE_GENERATED', key: 'PS_REVENUE_GENERATED' },
  { label: 'REGION', key: 'REGION' },
  { label: 'REP_ANNUAL_REVE_CMS', key: 'REP_ANNUAL_REVE_CMS' },
  { label: 'REP_ANNUAL_REVE_CS', key: 'REP_ANNUAL_REVE_CS' },
  { label: 'REP_ANNUAL_REVENUE', key: 'REP_ANNUAL_REVENUE' },
  { label: 'RLF_VALUE', key: 'RLF_VALUE' },
  { label: 'SUBSCRIPTION_Y1', key: 'SUBSCRIPTION_Y1' },
  { label: 'SUBSCRIPTION_Y2', key: 'SUBSCRIPTION_Y2' },
  { label: 'SUBSCRIPTION_Y3', key: 'SUBSCRIPTION_Y3' },
  { label: 'SUBSCRIPTION_Y4', key: 'SUBSCRIPTION_Y4' },
  { label: 'SUBSCRIPTION_Y5', key: 'SUBSCRIPTION_Y5' },
  { label: 'SUBSCRIPTION_Y6', key: 'SUBSCRIPTION_Y6' },
  { label: 'SUBSCRIPTION_Y7', key: 'SUBSCRIPTION_Y7' },
  { label: 'TEST_NUMERIC_MANDATO', key: 'TEST_NUMERIC_MANDATO' },
  { label: 'THIRD_PARTY_COGS', key: 'THIRD_PARTY_COGS' },
  { label: 'MULTIPLE_TEXT', key: 'MULTIPLE_TEXT' },
  { label: 'TEST_MULTY', key: 'TEST_MULTY' },
];
export const opportunityFields = [
  'opportunityId',
  'desc',
  'customer',
  'name',
  'handler',
  'salesman',
  'area',
  'stage',
  'probability',
  'reason',
  'estValue',
  'currency',
  'activ',
  'rootId',
  'oppRecordType',
  'forecastCategory',
  'exchangeRate',
  'estValueSys',
  'approvalStatus',
  'logExist',
  'noteExist',
  'contactExist',
  'taskExist',
  'itemExist',
  'attributeExist',
];
export const oppProductKeys = [
  'opportunityId',
  'itemId',
  'item',
  'itemDescription',
  'lineNumber',
  'desc',
  'ourPrice',
  'systemPrice',
  'quantity',
  'unit',
  'isFreeOfCharge',
];

export const opptProdHeaders = [
  { label: 'Opportunity Id', key: 'opportunityId' },
  { label: 'Item Id', key: 'itemId' },
  { label: 'Item', key: 'item' },
  { label: 'Item Desc', key: 'itemDescription' },
  { label: 'Line Number', key: 'lineNumber' },
  { label: 'Description', key: 'desc' },
  { label: 'Our Price', key: 'ourPrice' },
  { label: 'System Price', key: 'systemPrice' },
  { label: 'Quantity', key: 'quantity' },
  { label: 'Unit', key: 'unit' },
  { label: 'Is Free Of Charge', key: 'isFreeOfCharge' },
];

export const oppContactKeys = ['opportunityId', 'contactId', 'contactPerson', 'contactDC', 'email', 'phone', 'mobile', 'fax'];
export const opptContHeaders = [
  { label: 'Opportunity Id', key: 'opportunityId' },
  { label: 'Contact Id', key: 'contactId' },
  { label: 'contact Person', key: 'contactPerson' },
  { label: 'Contact DC', key: 'contactDC' },
  { label: 'Email', key: 'email' },
  { label: 'Phone', key: 'phone' },
  { label: 'Mobile', key: 'mobile' },
  { label: 'Fax', key: 'fax' },
];

export const customerContactHeaderKeys = [
  'businessPartner',
  'contactDC',
  'contactPerson',
  'isPublicContact',
  'userID',
  'email',
  'phone',
  'mobile',
  'fax',
];
export const customerContactHeaders = [
  { label: 'BusinessPartner Id', key: 'businessPartner' },
  { label: 'Contact DC', key: 'contactDC' },
  { label: 'contact Person', key: 'contactPerson' },
  { label: 'Public Contact', key: 'isPublicContact' },
  { label: 'User ID Id', key: 'userID' },
  { label: 'Email', key: 'email' },
  { label: 'Phone', key: 'phone' },
  { label: 'Mobile', key: 'mobile' },
  { label: 'Fax', key: 'fax' },
];
